
[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "None"
opacity = 0.9
blur = true

[font]
normal.family = "FiraCode Nerd Font Mono"
# normal.family = "SauceCodePro Nerd Font Mono"
# normal.family = "Hack Nerd Font Mono"
# normal.family = "UbuntuMono Nerd Font Mono"
# normal.family = "DejaVuSansM Nerd Font Mono"
#normal.family = "JetBrainsMono NF"

#regular
size = 12

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin_frappe.toml"]

#for video
# size = 35.0
